[package]
name = "bee_graph"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror.workspace = true

[features]
default = []
neo4j = []
nebulagraph = []
arangodb = []

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
