# Copyright (c) 2026 erik <erik@erik.xyz> — https://erik.xyz
[package]
name = "bee_tsdb"
version.workspace = true
edition.workspace = true

[dependencies]
async-trait = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
thiserror.workspace = true
chrono = { version = "0.4", features = ["serde"] }

[features]
default = []
influxdb = []
iotdb = []
questdb = []

[dev-dependencies]
tokio = { workspace = true, features = ["rt", "macros"] }
